export const copy = {
  en: {
    brand: "Enterprise ERP",
    tagline: "Foundation shell for a modular ERP platform",
    workspace: "Workspace",
    moduleLaunchpad: "Module launchpad",
    systemHealth: "System health",
    releaseReadiness: "Release readiness",
    operationsPulse: "Operations pulse",
    locale: "AR",
    theme: "Theme",
    navGroups: {
      access: "Access",
      people: "People",
      finance: "Finance",
      operations: "Operations",
      system: "System",
    },
  },
  ar: {
    brand: "نظام ERP المؤسسي",
    tagline: "هيكل تأسيسي لمنصة ERP معيارية",
    workspace: "مساحة العمل",
    moduleLaunchpad: "لوحة الوحدات",
    systemHealth: "حالة النظام",
    releaseReadiness: "جاهزية الإصدار",
    operationsPulse: "نبض العمليات",
    locale: "EN",
    theme: "المظهر",
    navGroups: {
      access: "الوصول",
      people: "الموظفون",
      finance: "المالية",
      operations: "العمليات",
      system: "النظام",
    },
  },
} as const;
