import {
  Activity,
  Banknote,
  Bell,
  Boxes,
  ChartColumn,
  Clock3,
  CreditCard,
  FileText,
  LayoutDashboard,
  Mail,
  Package,
  Shield,
  Users,
  Wallet,
  Workflow,
} from "lucide-react";

export const navigation = [
  { label: "Dashboard", icon: LayoutDashboard },
  { label: "Authentication", icon: Shield },
  { label: "Users", icon: Users },
  { label: "HR", icon: Workflow },
  { label: "Attendance", icon: Clock3 },
  { label: "Payroll", icon: Wallet },
  { label: "Accounting", icon: Banknote },
  { label: "Expenses", icon: CreditCard },
  { label: "Inventory", icon: Boxes },
  { label: "Manufacturing", icon: Package },
  { label: "Notifications", icon: Bell },
  { label: "Email", icon: Mail },
  { label: "Reports", icon: ChartColumn },
  { label: "Audit", icon: Activity },
  { label: "Documents", icon: FileText },
] as const;
